export const veryberry = '#B53471'
export const barared = '#ED4C67'
export const energos = '#C4E538'
export const redpigment = '#EA2027'
export const white = '#fff'
export const gray = '#7f8c8d'
export const lightgray = '#ecf0f1'
